# Generated by Django 4.1.6 on 2023-02-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("abbr", models.CharField(max_length=5)),
                ("symbol", models.CharField(max_length=1)),
            ],
        ),
    ]
