# Generated by Django 4.1.6 on 2023-02-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
        ("vehicles", "0002_vehicle_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="currency.currency",
            ),
        ),
    ]
