# Generated by Django 4.1.6 on 2023-02-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_currency"),
        ("vehicles", "0003_alter_vehicle_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
            preserve_default=False,
        ),
    ]
